### ISSUE TITLE
Use dill as default pickler

### ISSUE THREAD

**Issue by phenolophthaleinum** [777moneymaker/TadPole#10]
Please consider, dill is more reliable 
[Stack answer](https://stackoverflow.com/questions/58193119/how-is-dill-different-from-pythons-pickle-module)

**Comment by 777moneymaker** [comment]
# Branch z implem
@phenolophthaleinum Proponuję żebyś zrobił brancha z propozycją implementacji. Po jego zrobieniu oznacz go tutaj.

**Comment by phenolophthaleinum** [comment]
@777moneymaker 
Jest implementacja: [](https://github.com/777moneymaker/TadPole/blob/impl/pickle2dill/parsers/pajtonparser/pajtonparser.py)
