### ISSUE TITLE
Multiple occurences of the same phrog corresponding to one prot_id

### ISSUE THREAD

**Issue by ukmrs** [777moneymaker/TadPole#9]
# the problem:
*consider this*

**NC_021072.csv** *line=212* + header

```text
prot_id        hmm_id       prot_start  prot_end  evalue    score
NC_021072|205  phrog_701    2           2200      0.0       3421.7
NC_021072|205  phrog_18802  2220        2297      0.0       54.1
NC_021072|205  phrog_18802  2307        2746      0.0       534.1
NC_021072|205  phrog_5342   2797        2905      5.1e-157  52.0
NC_021072|205  phrog_701    2953        3060      0.0       76.0
NC_021072|205  phrog_18802  3069        3240      0.0       79.2
NC_021072|205  phrog_18802  3248        3407      0.0       50.6
NC_021072|205  phrog_5342   3420        3867      5.1e-157  103.2
NC_021072|205  phrog_701    4048        5156      0.0       1448.4
```

there are:
- four **phrog_18802**
- three **phrog_701**
- two **phrog_5342**

all asigned to NC_021072|205
# actions to take:
we have to make an informed decision about how our parser should handle those cases

**Comment by aziele** [comment]
Jakub already answered this question on MsTeams (see the attached figure). Briefly, if multiple PHROGs are assigned to a gene, all PHROGs should be included in the parsing results according to their order in the gene. In your example, gene `NC_021072|205` should be represented as:

```
phrog_701, phrog_18802, phrog_18802, phrog_5342, phrog_701, phrog_18802, phrog_18802, phrog_5342, phrog_701
````

Of note, if gene `NC_021072|205` was on the minus strand (according to GFF), then the above series of PHROGs would also be reveresed:

```
phrog_701, phrog_5342, phrog_18802, phrog_18802, phrog_701, phrog_5342, phrog_18802, phrog_18802, phrog_701
```

![MicrosoftTeams-image](https://user-images.githubusercontent.com/1017422/205906587-80750976-6650-40fb-b367-d2af643a8052.png)

**Comment by phenolophthaleinum** [comment]
@777moneymaker @LeonessaDeArgentum 
Isn't it fixed now?

**Comment by 777moneymaker** [comment]
@phenolophthaleinum
### Nope

@LeonessaDeArgentum fixed a problem with collapsing and reversing only. This should be fixed by removing `remove_duplicates` method from `PondMap` class and adjusting the collapsing of the jokers by constraining it to only to the unknown proteins. Right now collapsing works like this - iteratres through pair of objects and removes obj if prev is the same. So if all phrogs are different and jokers are adjacent, then only a single joker will remain. But if we allow duplicates of the phrogs to be adjacent to each other in list, then it'll remove them too. We have to make a fix.

**Comment by 777moneymaker** [comment]
@ukmrs You've been assigned to perform a fix on a branch that's assigned to this issue (`fix/duplicated-phrogs-fix`)

**Comment by phenolophthaleinum** [comment]
> @phenolophthaleinum
> ### Nope
> 
> @LeonessaDeArgentum fixed a problem with collapsing and reversing only. This should be fixed by removing `remove_duplicates` method from `PondMap` class and adjusting the collapsing of the jokers by constraining it to only to the unknown proteins. Right now collapsing works like this - iteratres through pair of objects and removes obj if prev is the same. So if all phrogs are different and jokers are adjacent, then only a single joker will remain. But if we allow duplicates of the phrogs to be adjacent to each other in list, then it'll remove them too. We have to make a fix.

Alright, understood👍

**Comment by 777moneymaker** [comment]
@phenolophthaleinum U can also do it if you want 😁

**Comment by phenolophthaleinum** [comment]
> @phenolophthaleinum U can also do it if you want 😁

If I could look up the code in peace, then maybe, but @ukmrs is the top tier specialist xD

**Comment by ukmrs** [comment]
I am on it
